name: 3 tests

on:
#  schedule:
#    - cron: "15 3 * * *"
  workflow_dispatch:


permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run autotests
    steps:
      - name: Download repository
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: install dependencies
        run: pip install -r requirements.txt
             pip install pytest
#      - name: Download all workflow run artifacts
#        uses: actions/download-artifact@v4.1.4

      - name: tests
        # if: "github.event.inputs.deployment_target == 'all'"
        run:  pytest tests --browser webkit --browser firefox --browser chromium
        continue-on-error: true

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '17'
